# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-18 03:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('info', models.TextField(blank=True, null=True, verbose_name='Additional Information')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1024)),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('group', models.CharField(blank=True, max_length=1024, null=True)),
                ('info', models.TextField(blank=True, null=True, verbose_name='Additional Information')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1024)),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('group', models.CharField(blank=True, max_length=1024, null=True)),
                ('expiration', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('info', models.TextField(blank=True, null=True, verbose_name='Additional Information')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineStockChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('when', models.DateTimeField(default=datetime.datetime.now)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='nursing.Medicine')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('info', models.TextField(blank=True, null=True, verbose_name='Additional Information')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('address', models.CharField(blank=True, max_length=1024, null=True)),
                ('contact', models.CharField(blank=True, max_length=1024, null=True)),
                ('pmh', models.TextField(blank=True, null=True, verbose_name='Personal Medical History')),
                ('alergies', models.TextField(blank=True, null=True)),
                ('when', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Registration Datetime')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Additional Information')),
            ],
        ),
        migrations.CreateModel(
            name='PatientType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('info', models.TextField(blank=True, null=True, verbose_name='Additional Information')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1024)),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('group', models.CharField(blank=True, max_length=1024, null=True)),
                ('info', models.TextField(blank=True, null=True, verbose_name='Additional Information')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Visit Datetime')),
                ('symptoms', models.TextField(blank=True, null=True, verbose_name='Signs and Symptoms')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Additional Information')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='nursing.Department')),
                ('diagnosys', models.ManyToManyField(blank=True, to='nursing.Diagnosys')),
                ('medicines', models.ManyToManyField(through='nursing.MedicineStockChange', to='nursing.Medicine')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='nursing.Patient')),
                ('treatments', models.ManyToManyField(blank=True, to='nursing.Treatment')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='nursing.PatientType'),
        ),
        migrations.AddField(
            model_name='medicinestockchange',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='nursing.Visit'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='medicine_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='nursing.MedicineType'),
        ),
    ]
