# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-19 11:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nursing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='nurse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
